
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";




import App from "./pages/App.tsx";

export const userRoutes: RouteObject[] = [



	{ path: "/", element: <App /> },

];
